// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK7cHXDmDRjD-iwKnYiYUVPx57KnTHAJ0',
    appId: '1:548632108326:web:766957803db44ce066b5e7',
    messagingSenderId: '548632108326',
    projectId: 'incog-d7aea',
    authDomain: 'incog-d7aea.firebaseapp.com',
    storageBucket: 'incog-d7aea.appspot.com',
    measurementId: 'G-GET65NTBHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtaJK11v0aFHTCfNYrg7u8LXdfj0U8Ono',
    appId: '1:548632108326:android:b87935bfae4f01e666b5e7',
    messagingSenderId: '548632108326',
    projectId: 'incog-d7aea',
    storageBucket: 'incog-d7aea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgpk3eoS6HkQKkhk78o6NO4uIh_X-xFc8',
    appId: '1:548632108326:ios:786fe8fa54603d7366b5e7',
    messagingSenderId: '548632108326',
    projectId: 'incog-d7aea',
    storageBucket: 'incog-d7aea.appspot.com',
    iosBundleId: 'com.example.incog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgpk3eoS6HkQKkhk78o6NO4uIh_X-xFc8',
    appId: '1:548632108326:ios:3c9f989b7ab8eba066b5e7',
    messagingSenderId: '548632108326',
    projectId: 'incog-d7aea',
    storageBucket: 'incog-d7aea.appspot.com',
    iosBundleId: 'com.example.incog.RunnerTests',
  );
}
